let paramSearch = 'All';
const catalogProduct = [
    {
        id: 'id1',
        name: 'Процессор AMD Ryzen 5 3600',
        img: './img/goods/amd_main.jpg',
        img2: './img/goods/amd_3600.jpg',
        img3: './img/goods/amd_last.jpg',
        price: 453,
        manufacturers: 'AMD',
        description: 'Matisse, AM4, 6 ядер, частота 4.2/3.6 ГГц, кэш 3 МБ + 32 МБ, техпроцесс 7 нм, TDP 65W',
        lineup: 'Ryzen 5',
        deliveryType: 'OEM',
        coolingIncluded: '-',
        crystalCodeName: 'Matisse',
        socket: 'AM4',
        numberOfCores: '6',
        maximumNumberOfThreads: '12',
        baseClock: '3.8 ГГц',
        maximumFrequency: '4.4 ГГц'
    },
    {
        id: 'id2',
        name: 'Процессор AMD Ryzen 5 2600',
        img: './img/goods/amd_main.jpg',
        img2: './img/goods/amd_2600.jpg',
        img3: './img/goods/amd_last.jpg',
        price: 270,
        manufacturers: 'AMD',
        description: 'Pinnacle Ridge, AM4, 6 ядер, частота 3.9/3.4 ГГц, кэш 3 МБ + 16 МБ, техпроцесс 12 нм, TDP 65W',
        lineup: 'Ryzen 5',
        deliveryType: 'OEM',
        coolingIncluded: '-',
        crystalCodeName: 'Pinnacle Ridge',
        socket: 'AM4',
        numberOfCores: '6',
        maximumNumberOfThreads: '12',
        baseClock: '3.4 ГГц',
        maximumFrequency: '3.9 ГГц'
    },
    {
        id: 'id3',
        name: 'Процессор AMD Ryzen 5 1600',
        img: './img/goods/amd_main.jpg',
        img2: './img/goods/amd_1600.jpg',
        img3: './img/goods/amd_last.jpg',
        price: 240,
        manufacturers: 'AMD',
        description: 'Summit Ridge, AM4, 6 ядер, частота 3.6/3.2 ГГц, кэш 3 МБ + 16 МБ, техпроцесс 14 нм, TDP 65W',
        lineup: '',
        deliveryType: '',
        coolingIncluded: '',
        crystalCodeName: '',
        socket: '',
        numberOfCores: '',
        maximumNumberOfThreads: '',
        baseClock: '',
        maximumFrequency: ''    
    },
    {
        id: 'id4',
        name: 'Процессор Intel Core i5-9400F',
        img: './img/goods/intel_i5_9th.jpg',
        img2: './img/goods/intel_i5_9400F.jpg',
        img3: './img/goods/intel_i5_9400F_box.jpg',
        price: 375,
        manufacturers: 'Intel',
        description: 'Coffee Lake, LGA1151 v2, 6 ядер, частота 4.1/2.9 ГГц, кэш 9 МБ, техпроцесс 14 нм, TDP 65W',
        lineup: 'Core i5',
        deliveryType: 'OEM',
        coolingIncluded: '-',
        crystalCodeName: 'Coffee Lake',
        socket: 'LGA1151 v2',
        numberOfCores: '6',
        maximumNumberOfThreads: '6',
        baseClock: '2.9 ГГц',
        maximumFrequency: '4.1 ГГц'    
    },
    {
        id: 'id5',
        name: 'Процессор Intel Core i3-9100F',
        img: './img/goods/intel_i3_9th.jpg',
        img2: './img/goods/intel_i3_9100F.jpg',
        img3: './img/goods/intel_i3_9100F_box.jpg',
        price: 178,
        manufacturers: 'Intel',
        description: 'Coffee Lake, LGA1151 v2, 4 ядра, частота 4.2/3.6 ГГц, кэш 6 МБ, техпроцесс 14 нм, TDP 65W',
        lineup: '',
        deliveryType: '',
        coolingIncluded: '',
        crystalCodeName: '',
        socket: '',
        numberOfCores: '',
        maximumNumberOfThreads: '',
        baseClock: '',
        maximumFrequency: '' 
    },
    {
        id: 'id6',
        name: 'Процессор Intel Core i7-9700K',
        img: './img/goods/intel_i7_9th.jpg',
        img2: './img/goods/intel_i7_9700K.jpg',
        img3: './img/goods/intel_i7_9700K_box.jpg',
        price: 1027,
        manufacturers: 'Intel',
        description: 'Coffee Lake, LGA1151 v2, 8 ядер, частота 4.9/3.6 ГГц, кэш 12 МБ, техпроцесс 14 нм, TDP 95W',
        lineup: '',
        deliveryType: '',
        coolingIncluded: '',
        crystalCodeName: '',
        socket: '',
        numberOfCores: '',
        maximumNumberOfThreads: '',
        baseClock: '',
        maximumFrequency: '' 
    },
    {
        id: 'id7',
        name: 'Crucial Ballistix Sport LT 2x8GB DDR4 PC4-25600',
        img: './img/goods/ram/crucialBallistixSport.jpg',
        img2: './img/goods/ram/crucialBallistixSport_2.jpg',
        img3: './img/goods/ram/crucialBallistixSport_3.jpg',
        price: 234,
        manufacturers: 'Crucial',
        description: '2 модуля, частота 3200 МГц, CL 16T, тайминги 16-18-18, напряжение 1.35 В',
        set: '2 модуля',
        memory: '16 ГБ',
        type: 'DDR4 DIMM',
        ecc: '-',
        frequency: '3200 МГц',
        pcindex: 'PC4-25600',
        casLatency: '16T',
        timings: '16-18-18',
        supplyVoltage: '1.35 В' 

    },
    {
        id: 'id8',
        name: 'HyperX Fury 2x8GB DDR4 PC4-21300',
        img: './img/goods/ram/hyperXFury.jpg',
        img2: './img/goods/ram/hyperXFury_2.jpg',
        img3: './img/goods/ram/hyperXFury_3.jpg',
        price: 208,
        manufacturers: 'HyperX',
        description: '2 модуля, частота 2666 МГц, CL 16T, тайминги 16-18-18, напряжение 1.2 В',
        set: '',
        memory: '',
        type: '',
        ecc: '',
        frequency: '',
        pcindex: '',
        casLatency: '',
        timings: '',
        supplyVoltage: '' 
    },
    {
        id: 'id9',
        name: 'Kingston 32GB DDR4 PC4-19200',
        img: './img/goods/ram/kingston.jpg',
        img2: './img/goods/ram/kingston_2.jpg',
        img3: './img/goods/ram/kingston_3.jpg',
        price: 698,
        manufacturers: 'Kingston',
        description: '1 модуль, частота 2666 МГц, CL 19T, напряжение 1.2 В',
        set: '',
        memory: '',
        type: '',
        ecc: '',
        frequency: '',
        pcindex: '',
        casLatency: '',
        timings: '',
        supplyVoltage: '' 
    },
    {
        id: 'id10',
        name: 'Блок питания Chieftec Proton BDF-500S',
        img: './img/goods/powerSupply/chieftec.jpg',
        img2: './img/goods/powerSupply/chieftec_2.jpg',
        img3: './img/goods/powerSupply/chieftec_3.jpg',
        price: 116,
        manufacturers: 'Chieftec',
        description: 'Активная PFC, КПД 85%, бронзовый сертификат, вентилятор 1x120 мм, 12V 41.7 А',
        power: '500 Вт',        
        powerSupplyStandard: 'ATX12V 2.3',
        numberOfIndividualLines: '1',        
        maxLineCurrent: '41.68 А',
        pfc: 'Активная',
        efficiency: '85 %',        
        certificate80Plus: 'Бронзовый',        
        powerSupplyFanSize: '120 мм',        
        numberOfFans: '1',        
        fanBbacklight: '-'
    }
    
]